training_data = [
    # ==========================================
    # CLASS 0: FAN (100 Sentences)
    # ==========================================
    ("turn on the fan", 0), ("switch on the fan", 0), ("start the fan", 0), ("can you start the fan", 0),
    ("power on the fan", 0), ("activate the fan", 0), ("boot up the fan", 0), ("get the fan going", 0),
    ("spin up the fan", 0), ("kick on the fan", 0), ("turn off the fan", 0), ("switch off the fan", 0),
    ("stop the fan", 0), ("can you stop the fan", 0), ("power off the fan", 0), ("deactivate the fan", 0),
    ("shut down the fan", 0), ("kill the fan", 0), ("turn the fan off", 0), ("cut the fan power", 0),
    ("it is hot in here", 0), ("it is getting warm", 0), ("i am sweating", 0), ("the room is boiling", 0),
    ("it is baking inside", 0), ("i need some cool air", 0), ("the air is stifling", 0), ("it feels like an oven", 0),
    ("it is too hot", 0), ("i need a breeze", 0), ("it is very stuffy", 0), ("the air is stagnant", 0),
    ("it feels humid", 0), ("the room needs ventilation", 0), ("i need some airflow", 0), ("the room is suffocating", 0),
    ("it is hard to breathe", 0), ("the air is heavy", 0), ("it feels claustrophobic", 0), ("there is no air circulation", 0),
    ("increase the fan speed", 0), ("make the fan faster", 0), ("crank up the fan", 0), ("turn up the fan speed", 0),
    ("set the fan to high", 0), ("accelerate the fan", 0), ("make it blow harder", 0), ("boost the fan", 0),
    ("put the fan on max", 0), ("give me more air", 0), ("decrease the fan speed", 0), ("make the fan slower", 0),
    ("turn down the fan", 0), ("slow down the fan", 0), ("set the fan to low", 0), ("reduce the airflow", 0),
    ("make the fan quieter", 0), ("lower the fan setting", 0), ("put the fan on minimum", 0), ("less breeze please", 0),
    ("oscillate the fan", 0), ("make the fan swing", 0), ("turn on fan rotation", 0), ("start fan oscillation", 0),
    ("make the fan move side to side", 0), ("stop the fan oscillation", 0), ("keep the fan steady", 0), ("stop fan rotation", 0),
    ("lock the fan position", 0), ("make the fan blow in one direction", 0), ("toggle the fan", 0), ("change the fan setting", 0),
    ("reset the fan", 0), ("check the fan status", 0), ("is the fan running", 0), ("the ceiling fan needs to start", 0),
    ("power up the ceiling fan", 0), ("shut off the ceiling fan", 0), ("table fan on", 0), ("table fan off", 0),
    ("exhaust fan on", 0), ("exhaust fan off", 0), ("start the exhaust", 0), ("kill the exhaust", 0),
    ("the cooling fan is required", 0), ("disengage the fan", 0), ("engage the fan", 0), ("run the fan script", 0),
    ("execute fan command", 0), ("the ventilation is poor", 0), ("clear out the stuffy air", 0), ("freshen up the room", 0),
    ("circulate the air", 0), ("get some air moving", 0), ("blow some cold air", 0), ("initiate the fan sequence", 0),
    ("terminate the fan process", 0), ("fan speed up", 0), ("fan speed down", 0), ("kill the fan relay", 0),

    # ==========================================
    # CLASS 1: LAMP (100 Sentences)
    # ==========================================
    ("turn on the lamp", 1), ("switch on the lamp", 1), ("start the lamp", 1), ("can you start the lamp", 1),
    ("power on the lamp", 1), ("activate the lamp", 1), ("illuminate the lamp", 1), ("get the lamp going", 1),
    ("light up the lamp", 1), ("kick on the lamp", 1), ("turn off the lamp", 1), ("switch off the lamp", 1),
    ("stop the lamp", 1), ("can you stop the lamp", 1), ("power off the lamp", 1), ("deactivate the lamp", 1),
    ("extinguish the lamp", 1), ("kill the lamp", 1), ("turn the lamp off", 1), ("cut the lamp power", 1),
    ("i am reading a book", 1), ("i need reading light", 1), ("time to study", 1), ("i am opening my textbook", 1),
    ("i need desk illumination", 1), ("let us light up the desk", 1), ("prepare my study space", 1), ("i am sitting at my desk", 1),
    ("i need direct light", 1), ("brighten up the table", 1), ("it is too dark on my desk", 1), ("i cannot see my notebook", 1),
    ("shadows on my book", 1), ("illuminate my papers", 1), ("need focused lighting", 1), ("turn on the study light", 1),
    ("turn off the study light", 1), ("power up the table lamp", 1), ("shut down the table lamp", 1), ("desk light active", 1),
    ("brighten the lamp", 1), ("make the lamp brighter", 1), ("crank up the lamp", 1), ("turn up the lamp brightness", 1),
    ("set the lamp to max", 1), ("increase lamp intensity", 1), ("more lamp light", 1), ("boost the lamp output", 1),
    ("make the desk brighter", 1), ("maximize lamp light", 1), ("dim the lamp", 1), ("make the lamp softer", 1),
    ("turn down the lamp", 1), ("lower the lamp brightness", 1), ("set the lamp to low", 1), ("reduce lamp intensity", 1),
    ("make the lamp dim", 1), ("lower the lamp setting", 1), ("put the lamp on minimum", 1), ("less lamp light please", 1),
    ("change the lamp color", 1), ("make the lamp warm", 1), ("set the lamp to white", 1), ("make the lamp yellow", 1),
    ("soft lamp light", 1), ("night mode for the lamp", 1), ("set lamp to reading mode", 1), ("cool white lamp", 1),
    ("warm tone lamp", 1), ("adjust lamp spectrum", 1), ("toggle the lamp", 1), ("change the lamp setting", 1),
    ("reset the lamp", 1), ("check the lamp status", 1), ("is the lamp burning", 1), ("the bedside lamp needs to start", 1),
    ("power up the bedside lamp", 1), ("shut off the bedside lamp", 1), ("floor lamp on", 1), ("floor lamp off", 1),
    ("nightstand light on", 1), ("nightstand light off", 1), ("start the nightstand light", 1), ("kill the nightstand light", 1),
    ("the reading lamp is required", 1), ("disengage the lamp", 1), ("engage the lamp", 1), ("run the lamp script", 1),
    ("execute lamp command", 1), ("the table is dark", 1), ("clear out the desk shadows", 1), ("freshen up the desk space", 1),
    ("focus the lamp light", 1), ("get some local light", 1), ("shine the lamp here", 1), ("initiate the lamp sequence", 1),
    ("terminate the lamp process", 1), ("lamp intensity up", 1), ("lamp intensity down", 1), ("kill the lamp relay", 1),

    # ==========================================
    # CLASS 2: LIGHT (100 Sentences)
    # ==========================================
    ("turn on the light", 2), ("switch on the light", 2), ("start the light", 2), ("can you start the light", 2),
    ("power on the light", 2), ("activate the light", 2), ("illuminate the room", 2), ("get the light going", 2),
    ("light up the room", 2), ("kick on the light", 2), ("turn off the light", 2), ("switch off the light", 2),
    ("stop the light", 2), ("can you stop the light", 2), ("power off the light", 2), ("deactivate the light", 2),
    ("extinguish the light", 2), ("kill the light", 2), ("turn the light off", 2), ("cut the light power", 2),
    ("it is dark in here", 2), ("it is getting pitch black", 2), ("i cannot see anything", 2), ("the room is gloomy", 2),
    ("it is completely blind inside", 2), ("i need some illumination", 2), ("the visibility is zero", 2), ("it feels like night", 2),
    ("it is too dark", 2), ("i need main lights", 2), ("it is very dim", 2), ("the shadows are everywhere", 2),
    ("it feels depressing here", 2), ("the room needs clarity", 2), ("i need ceiling light", 2), ("the room is pitch dark", 2),
    ("i am tripping over things", 2), ("the ambient light is low", 2), ("it feels spooky", 2), ("there is no light source", 2),
    ("increase the light brightness", 2), ("make the light brighter", 2), ("crank up the overhead light", 2), ("turn up the room brightness", 2),
    ("set the light to high", 2), ("accelerate the illumination", 2), ("make it shine harder", 2), ("boost the main light", 2),
    ("put the light on max", 2), ("give me more overhead illumination", 2), ("dim the overhead light", 2), ("make the light softer", 2),
    ("turn down the light", 2), ("lower the room brightness", 2), ("set the light to low", 2), ("reduce light intensity", 2),
    ("make the room dim", 2), ("lower the light setting", 2), ("put the light on minimum", 2), ("less ambient light please", 2),
    ("change the light color", 2), ("make the light warm", 2), ("set the light to white", 2), ("make the light yellow", 2),
    ("soft room light", 2), ("night mode for the overheads", 2), ("set light to ambient mode", 2), ("cool white illumination", 2),
    ("warm tone illumination", 2), ("adjust ceiling light spectrum", 2), ("toggle the light", 2), ("change the light setting", 2),
    ("reset the light", 2), ("check the light status", 2), ("is the light running", 2), ("the ceiling light needs to start", 2),
    ("power up the ceiling light", 2), ("shut off the ceiling light", 2), ("main light on", 2), ("main light off", 2),
    ("room light on", 2), ("room light off", 2), ("start the main light", 2), ("kill the main light", 2),
    ("the room lighting is required", 2), ("disengage the light", 2), ("engage the light", 2), ("run the light script", 2),
    ("execute light command", 2), ("the surroundings are obscure", 2), ("clear out the room shadows", 2), ("freshen up the environment", 2),
    ("flood the room with light", 2), ("get some main light moving", 2), ("shine the ceiling led", 2), ("initiate the light sequence", 2),
    ("terminate the light process", 2), ("light brightness up", 2), ("light brightness down", 2), ("kill the light relay", 2),

    # ==========================================
    # CLASS 3: CAMERA (100 Sentences)
    # ==========================================
    ("turn on the camera", 3), ("switch on the camera", 3), ("start the camera", 3), ("can you start the camera", 3),
    ("power on the camera", 3), ("activate the camera", 3), ("boot up the camera", 3), ("get the camera going", 3),
    ("spin up the camera sensor", 3), ("kick on the camera", 3), ("turn off the camera", 3), ("switch off the camera", 3),
    ("stop the camera", 3), ("can you stop the camera", 3), ("power off the camera", 3), ("deactivate the camera", 3),
    ("shut down the camera", 3), ("kill the camera", 3), ("turn the camera off", 3), ("cut the camera power", 3),
    ("i need to monitor the room", 3), ("start surveillance", 3), ("begin recording video", 3), ("watch the space", 3),
    ("keep an eye on the door", 3), ("stream the live feed", 3), ("open the video stream", 3), ("turn on security monitoring", 3),
    ("i want to check the perimeter", 3), ("record this moment", 3), ("capture a video clip", 3), ("start the optic tracking", 3),
    ("monitor the entryway", 3), ("turn on the webcam", 3), ("deactivate security logging", 3), ("shut down the lens", 3),
    ("is anyone outside", 3), ("show me the feedback look", 3), ("observe the laboratory setup", 3), ("capture an image", 3),
    ("increase camera resolution", 3), ("make the camera pan faster", 3), ("crank up the camera contrast", 3), ("turn up the exposure", 3),
    ("set camera frame rate to high", 3), ("zoom in the camera", 3), ("make the lens zoom close", 3), ("boost video gain", 3),
    ("put the zoom on max", 3), ("widen the camera view", 3), ("decrease camera resolution", 3), ("zoom out the lens", 3),
    ("turn down exposure", 3), ("slow down the camera pan", 3), ("set frame rate to low", 3), ("reduce video contrast", 3),
    ("make the lens pull back", 3), ("lower the camera sensitivity", 3), ("put zoom on minimum", 3), ("less exposure please", 3),
    ("pan the camera left", 3), ("tilt the camera down", 3), ("turn on motion tracking", 3), ("start face detection", 3),
    ("make the camera follow me", 3), ("stop camera tracking", 3), ("keep the camera fixed", 3), ("stop lens autofocus", 3),
    ("lock camera position", 3), ("make the lens stay still", 3), ("toggle the camera", 3), ("change the camera mode", 3),
    ("reset the camera", 3), ("check the camera status", 3), ("is the camera recording", 3), ("the security lens needs to start", 3),
    ("power up security camera", 3), ("shut off security camera", 3), ("webcam on", 3), ("webcam off", 3),
    ("cctv on", 3), ("cctv off", 3), ("start the cctv feed", 3), ("kill the cctv network", 3),
    ("the visual sensor is required", 3), ("disengage the camera", 3), ("engage the camera", 3), ("run the camera script", 3),
    ("execute camera command", 3), ("the surveillance loop is blind", 3), ("clear out the camera buffer", 3), ("freshen up the video frame", 3),
    ("initialize image capture", 3), ("get some video moving", 3), ("run the optics pipeline", 3), ("initiate camera sequence", 3),
    ("terminate camera process", 3), ("camera zoom up", 3), ("camera zoom down", 3), ("kill the camera feed", 3)
]
