training_data = [
    # ==========================================
    # CLASS 0: FAN (250 Sentences)
    # ==========================================
    ("turn on the fan", 0), ("switch on the fan", 0), ("start the fan", 0), ("can you start the fan", 0),
    ("power on the fan", 0), ("activate the fan", 0), ("boot up the fan", 0), ("get the fan going", 0),
    ("spin up the fan", 0), ("kick on the fan", 0), ("turn off the fan", 0), ("switch off the fan", 0),
    ("stop the fan", 0), ("can you stop the fan", 0), ("power off the fan", 0), ("deactivate the fan", 0),
    ("shut down the fan", 0), ("kill the fan", 0), ("turn the fan off", 0), ("cut the fan power", 0),
    ("it is hot in here", 0), ("it is getting warm", 0), ("i am sweating", 0), ("the room is boiling", 0),
    ("it is baking inside", 0), ("i need some cool air", 0), ("the air is stifling", 0), ("it feels like an oven", 0),
    ("it is too hot", 0), ("i need a breeze", 0), ("it is very stuffy", 0), ("the air is stagnant", 0),
    ("it feels humid", 0), ("the room needs ventilation", 0), ("i need some airflow", 0), ("the room is suffocating", 0),
    ("it is hard to breathe", 0), ("the air is heavy", 0), ("it feels claustrophobic", 0), ("there is no air circulation", 0),
    ("increase the fan speed", 0), ("make the fan faster", 0), ("crank up the fan", 0), ("turn up the fan speed", 0),
    ("set the fan to high", 0), ("accelerate the fan", 0), ("make it blow harder", 0), ("boost the fan", 0),
    ("put the fan on max", 0), ("give me more air", 0), ("decrease the fan speed", 0), ("make the fan slower", 0),
    ("turn down the fan", 0), ("slow down the fan", 0), ("set the fan to low", 0), ("reduce the airflow", 0),
    ("make the fan quieter", 0), ("lower the fan setting", 0), ("put the fan on minimum", 0), ("less breeze please", 0),
    ("oscillate the fan", 0), ("make the fan swing", 0), ("turn on fan rotation", 0), ("start fan oscillation", 0),
    ("make the fan move side to side", 0), ("stop the fan oscillation", 0), ("keep the fan steady", 0), ("stop fan rotation", 0),
    ("lock the fan position", 0), ("make the fan blow in one direction", 0), ("toggle the fan", 0), ("change the fan setting", 0),
    ("reset the fan", 0), ("check the fan status", 0), ("is the fan running", 0), ("the ceiling fan needs to start", 0),
    ("power up the ceiling fan", 0), ("shut off the ceiling fan", 0), ("table fan on", 0), ("table fan off", 0),
    ("exhaust fan on", 0), ("exhaust fan off", 0), ("start the exhaust", 0), ("kill the exhaust", 0),
    ("the cooling fan is required", 0), ("disengage the fan", 0), ("engage the fan", 0), ("run the fan script", 0),
    ("execute fan command", 0), ("the ventilation is poor", 0), ("clear out the stuffy air", 0), ("freshen up the room", 0),
    ("circulate the air", 0), ("get some air moving", 0), ("blow some cold air", 0), ("initiate the fan sequence", 0),
    ("terminate the fan process", 0), ("fan speed up", 0), ("fan speed down", 0), ("kill the fan relay", 0),
    ("please start the fan", 0), ("activate the fan ceiling", 0), ("make the fan run faster", 0), ("can you spin the fan", 0),
    ("kick off the ceiling fan", 0), ("boot up the desk fan", 0), ("toggle the fan power", 0), ("power on the air blower", 0),
    ("switch on the cooling fan", 0), ("the fan needs to be turned on", 0), ("go ahead and start the fan", 0), ("engage the fan blades", 0),
    ("crank up the fan speed", 0), ("get the fan moving now", 0), ("enable the ceiling fan", 0), ("turn the fan to high", 0),
    ("begin spinning the fan", 0), ("fire up the bedroom fan", 0), ("set the fan to maximum", 0), ("start up the exhaust fan", 0),
    ("run the fan on low", 0), ("switch the fan to medium", 0), ("wake up the cooling fan", 0), ("give me some air turn on the fan", 0),
    ("it is getting warm start the fan", 0), ("stuffy in here activate the fan", 0), ("need a breeze spin the fan", 0), ("make the fan blow air", 0),
    ("turn on the fan immediately", 0), ("could you please turn on the fan", 0), ("would you mind starting the fan", 0), ("execute fan start command", 0),
    ("unleash the fan current", 0), ("get the desk fan going", 0), ("turn on the fan right away", 0), ("power up the ventilation fan", 0),
    ("start the fan in the room", 0), ("turn on the fan for me", 0), ("kick the fan into gear", 0), ("activate the main fan", 0),
    ("start the fan motor", 0), ("switch on the stand fan", 0), ("turn on the fan please", 0), ("let us get the fan spinning", 0),
    ("power on the giant fan", 0), ("activate the room fan", 0), ("turn on the fan unit", 0), ("engage the fan power now", 0),
    ("please stop the fan", 0), ("deactivate the fan ceiling", 0), ("make the fan shut down", 0), ("kill the ceiling fan", 0),
    ("shut down the desk fan", 0), ("toggle the fan off", 0), ("power off the air blower", 0), ("switch off the cooling fan", 0),
    ("the fan needs to be turned off", 0), ("go ahead and stop the fan", 0), ("disengage the fan blades", 0), ("crank down the fan speed", 0),
    ("get the fan to stop moving", 0), ("disable the ceiling fan", 0), ("turn the fan to zero", 0), ("cease spinning the fan", 0),
    ("cut power to the bedroom fan", 0), ("set the fan to off", 0), ("halt the exhaust fan", 0), ("stop the fan completely", 0),
    ("switch the fan off entirely", 0), ("put the cooling fan to sleep", 0), ("it is freezing turn off the fan", 0), ("getting cold stop the fan", 0),
    ("chilly in here deactivate the fan", 0), ("no more breeze stop the fan", 0), ("make the fan stop blowing", 0), ("turn off the fan immediately", 0),
    ("could you please turn off the fan", 0), ("would you mind stopping the fan", 0), ("execute fan stop command", 0), ("cut the fan current", 0),
    ("get the desk fan to stop", 0), ("turn off the fan right away", 0), ("power down the ventilation fan", 0), ("stop the fan in the room", 0),
    ("turn off the fan for me", 0), ("kick the fan out of gear", 0), ("deactivate the main fan", 0), ("stop the fan motor", 0),
    ("switch off the stand fan", 0), ("turn off the fan please", 0), ("let us stop the fan spinning", 0), ("power off the giant fan", 0),
    ("deactivate the room fan", 0), ("turn off the fan unit", 0), ("disengage the fan power now", 0), ("the room is boiling turn on the fan", 0),
    ("it is roasting inside activate the fan", 0), ("the air is stagnant start the fan", 0), ("it feels like a sauna spin the fan", 0), ("i need some fresh air turn on the fan", 0),
    ("circulate the air start the fan", 0), ("it is melting hot activate the fan", 0), ("suffocating in here spin the fan", 0), ("the humidity is high turn on the fan", 0),
    ("unbearably warm start the fan", 0), ("scorching day activate the fan", 0), ("i am burning up spin the fan", 0), ("the room needs ventilation turn on the fan", 0),
    ("breeze needed start the fan", 0), ("sweating bullets activate the fan", 0), ("stifling heat spin the fan", 0), ("need cooling down turn on the fan", 0),
    ("the air quality is bad start the fan", 0), ("it is baking in here activate the fan", 0), ("i am overheating spin the fan", 0), ("stuffy air everywhere turn on the fan", 0),
    ("sweat is dripping start the fan", 0), ("uncomfortable heat activate the fan", 0), ("need the exhaust spin the fan", 0), ("it is freezing cold turn off the fan", 0),
    ("i am shivering turn off the fan", 0), ("it is ice cold inside deactivate the fan", 0), ("the air is too drafty stop the fan", 0), ("it feels like winter spin the fan off", 0),
    ("i need to stay warm turn off the fan", 0), ("stop the circulation stop the fan", 0), ("it is brutally chilly deactivate the fan", 0), ("freezing in here spin the fan off", 0),
    ("the temperature dropped turn off the fan", 0), ("unbearably cold stop the fan", 0), ("frosty air activate the fan shutdown", 0), ("i am freezing up spin the fan down", 0),
    ("the room needs heat turn off the fan", 0), ("no more wind start the fan shutdown", 0), ("shivering violently deactivate the fan", 0), ("bitter cold spin the fan down", 0),
    ("need to trap heat turn off the fan", 0), ("the draft is too much stop the fan", 0), ("it is an icebox in here deactivate the fan", 0), ("i am turning into ice spin the fan off", 0),
    ("too much wind everywhere turn off the fan", 0), ("teeth are chattering stop the fan", 0), ("uncomfortable chill deactivate the fan", 0), ("need to stop the exhaust spin the fan off", 0),
    ("increase the fan velocity", 0), ("decrease the fan velocity", 0), ("boost the fan performance", 0), ("lower the fan performance", 0),
    ("crank the fan all the way up", 0), ("crank the fan all the way down", 0), ("adjust the fan setting to high", 0), ("adjust the fan setting to low", 0),
    ("more power to the fan", 0), ("less power to the fan", 0), ("speed up the rotating blades", 0), ("slow down the rotating blades", 0),
    ("maximize the air flow", 0), ("minimize the air flow", 0), ("the fan is too slow speed it up", 0), ("the fan is too loud slow it down", 0),
    ("put the fan on max power", 0), ("put the fan on min power", 0), ("accelerate the ventilation fan", 0), ("decelerate the ventilation fan", 0),
    ("give me full blast fan", 0), ("gentle breeze on the fan", 0), ("make the fan super fast", 0), ("make the fan super slow", 0),

    # ==========================================
    # CLASS 1: LAMP (250 Sentences)
    # ==========================================
    ("turn on the lamp", 1), ("switch on the lamp", 1), ("start the lamp", 1), ("can you start the lamp", 1),
    ("power on the lamp", 1), ("activate the lamp", 1), ("illuminate the lamp", 1), ("get the lamp going", 1),
    ("light up the lamp", 1), ("kick on the lamp", 1), ("turn off the lamp", 1), ("switch off the lamp", 1),
    ("stop the lamp", 1), ("can you stop the lamp", 1), ("power off the lamp", 1), ("deactivate the lamp", 1),
    ("extinguish the lamp", 1), ("kill the lamp", 1), ("turn the lamp off", 1), ("cut the lamp power", 1),
    ("i am reading a book", 1), ("i need reading light", 1), ("time to study", 1), ("i am opening my textbook", 1),
    ("i need desk illumination", 1), ("let us light up the desk", 1), ("prepare my study space", 1), ("i am sitting at my desk", 1),
    ("i need direct light", 1), ("brighten up the table", 1), ("it is too dark on my desk", 1), ("i cannot see my notebook", 1),
    ("shadows on my book", 1), ("illuminate my papers", 1), ("need focused lighting", 1), ("turn on the study light", 1),
    ("turn off the study light", 1), ("power up the table lamp", 1), ("shut down the table lamp", 1), ("desk light active", 1),
    ("brighten the lamp", 1), ("make the lamp brighter", 1), ("crank up the lamp", 1), ("turn up the lamp brightness", 1),
    ("set the lamp to max", 1), ("increase lamp intensity", 1), ("more lamp light", 1), ("boost the lamp output", 1),
    ("make the desk brighter", 1), ("maximize lamp light", 1), ("dim the lamp", 1), ("make the lamp softer", 1),
    ("turn down the lamp", 1), ("lower the lamp brightness", 1), ("set the lamp to low", 1), ("reduce lamp intensity", 1),
    ("make the lamp dim", 1), ("lower the lamp setting", 1), ("put the lamp on minimum", 1), ("less lamp light please", 1),
    ("change the lamp color", 1), ("make the lamp warm", 1), ("set the lamp to white", 1), ("make the lamp yellow", 1),
    ("soft lamp light", 1), ("night mode for the lamp", 1), ("set lamp to reading mode", 1), ("cool white lamp", 1),
    ("warm tone lamp", 1), ("adjust lamp spectrum", 1), ("toggle the lamp", 1), ("change the lamp setting", 1),
    ("reset the lamp", 1), ("check the lamp status", 1), ("is the lamp burning", 1), ("the bedside lamp needs to start", 1),
    ("power up the bedside lamp", 1), ("shut off the bedside lamp", 1), ("floor lamp on", 1), ("floor lamp off", 1),
    ("nightstand light on", 1), ("nightstand light off", 1), ("start the nightstand light", 1), ("kill the nightstand light", 1),
    ("the reading lamp is required", 1), ("disengage the lamp", 1), ("engage the lamp", 1), ("run the lamp script", 1),
    ("execute lamp command", 1), ("the table is dark", 1), ("clear out the desk shadows", 1), ("freshen up the desk space", 1),
    ("focus the lamp light", 1), ("get some local light", 1), ("shine the lamp here", 1), ("initiate the lamp sequence", 1),
    ("terminate the lamp process", 1), ("lamp intensity up", 1), ("lamp intensity down", 1), ("kill the lamp relay", 1),
    ("please start the lamp", 1), ("activate the lamp light", 1), ("make the lamp glow brighter", 1), ("can you switch the lamp", 1),
    ("kick off the desk lamp", 1), ("boot up the table lamp", 1), ("toggle the lamp power", 1), ("power on the reading lamp", 1),
    ("switch on the bedside lamp", 1), ("the lamp needs to be turned on", 1), ("go ahead and start the lamp", 1), ("engage the lamp switch", 1),
    ("crank up the lamp brightness", 1), ("get the lamp glowing now", 1), ("enable the standing lamp", 1), ("turn the lamp to high", 1),
    ("begin lighting the lamp", 1), ("fire up the bedroom lamp", 1), ("set the lamp to maximum", 1), ("start up the floor lamp", 1),
    ("run the lamp on dim", 1), ("switch the lamp to medium", 1), ("wake up the desk lamp", 1), ("give me some light turn on the lamp", 1),
    ("it is getting dark start the lamp", 1), ("pitch black in here activate the lamp", 1), ("need to read spin the lamp", 1), ("make the lamp emit light", 1),
    ("turn on the lamp immediately", 1), ("could you please turn on the lamp", 1), ("would you mind starting the lamp", 1), ("execute lamp start command", 1),
    ("unleash the lamp current", 1), ("get the desk lamp going", 1), ("turn on the lamp right away", 1), ("power up the study lamp", 1),
    ("start the lamp in the room", 1), ("turn on the lamp for me", 1), ("kick the lamp into gear", 1), ("activate the main lamp", 1),
    ("start the lamp bulb", 1), ("switch on the stand lamp", 1), ("turn on the lamp please", 1), ("let us get the lamp glowing", 1),
    ("power on the giant lamp", 1), ("activate the room lamp", 1), ("turn on the lamp unit", 1), ("engage the lamp power now", 1),
    ("please stop the lamp", 1), ("deactivate the lamp light", 1), ("make the lamp shut down", 1), ("can you stop the lamp", 1),
    ("kill the desk lamp", 1), ("shut down the table lamp", 1), ("toggle the lamp off", 1), ("power off the reading lamp", 1),
    ("switch off the bedside lamp", 1), ("the lamp needs to be turned off", 1), ("go ahead and stop the lamp", 1), ("disengage the lamp switch", 1),
    ("crank down the lamp brightness", 1), ("get the lamp to stop glowing", 1), ("disable the standing lamp", 1), ("turn the lamp to zero", 1),
    ("cease lighting the lamp", 1), ("cut power to the bedroom lamp", 1), ("set the lamp to off", 1), ("halt the floor lamp", 1),
    ("stop the lamp completely", 1), ("switch the lamp off entirely", 1), ("put the desk lamp to sleep", 1), ("it is blinding turn off the lamp", 1),
    ("getting too bright stop the lamp", 1), ("sun is up deactivate the lamp", 1), ("no more reading stop the lamp", 1), ("make the lamp stop emitting", 1),
    ("turn off the lamp immediately", 1), ("could you please turn off the lamp", 1), ("would you mind stopping the lamp", 1), ("execute lamp stop command", 1),
    ("cut the lamp current", 1), ("get the desk lamp to stop", 1), ("turn off the lamp right away", 1), ("power down the study lamp", 1),
    ("stop the lamp in the room", 1), ("turn off the lamp for me", 1), ("kick the lamp out of gear", 1), ("deactivate the main lamp", 1),
    ("stop the lamp bulb", 1), ("switch off the stand lamp", 1), ("turn off the lamp please", 1), ("let us stop the lamp glowing", 1),
    ("power off the giant lamp", 1), ("deactivate the room lamp", 1), ("turn off the lamp unit", 1), ("disengage the lamp power now", 1),
    ("the room is pitch black turn on the lamp", 1), ("i cannot see anything turn on the lamp", 1), ("it is dark inside activate the lamp", 1), ("the sunset happened start the lamp", 1),
    ("it feels like a cave spin the lamp", 1), ("i need to read my book turn on the lamp", 1), ("illuminate the workspace start the lamp", 1), ("it is night time activate the lamp", 1),
    ("groping in the dark spin the lamp", 1), ("the shadows are creepy turn on the lamp", 1), ("unbearably dark start the lamp", 1), ("gloomy day activate the lamp", 1),
    ("i am in total darkness spin the lamp", 1), ("the room needs brightness turn on the lamp", 1), ("light source needed start the lamp", 1), ("sun has set activate the lamp", 1),
    ("stifling darkness spin the lamp", 1), ("need illumination turn on the lamp", 1), ("the ambient light is low start the lamp", 1), ("it is dim in here activate the lamp", 1),
    ("i am straining my eyes spin the lamp", 1), ("shadowy air everywhere turn on the lamp", 1), ("daylight is fading start the lamp", 1), ("uncomfortable darkness activate the lamp", 1),
    ("need the nightstand spin the lamp", 1), ("it is blindingly bright turn off the lamp", 1), ("i am squinting turn off the lamp", 1), ("it is too bright inside deactivate the lamp", 1),
    ("the sun is bleeding in stop the lamp", 1), ("it feels like midday spin the lamp off", 1), ("i need to sleep turn off the lamp", 1), ("stop the illumination stop the lamp", 1),
    ("it is brutally glowing deactivate the lamp", 1), ("glaring in here spin the lamp off", 1), ("the room is lit up turn off the lamp", 1), ("unbearably bright stop the lamp", 1),
    ("radiant air activate the lamp shutdown", 1), ("i am shutting my eyes spin the lamp down", 1), ("the room needs darkness turn off the lamp", 1), ("no more light start the lamp shutdown", 1),
    ("squinting violently deactivate the lamp", 1), ("bitter glare spin the lamp down", 1), ("need to trap darkness turn off the lamp", 1), ("the glow is too much stop the lamp", 1),
    ("it is a greenhouse in here deactivate the lamp", 1), ("i am turning blind spin the lamp off", 1), ("too much glare everywhere turn off the lamp", 1), ("eyes are hurting stop the lamp", 1),
    ("uncomfortable brightness deactivate the lamp", 1), ("need to stop the bulb spin the lamp off", 1), ("increase the lamp luminance", 1), ("decrease the lamp luminance", 1),
    ("boost the lamp performance", 1), ("lower the lamp performance", 1), ("crank the lamp all the way up", 1), ("crank the lamp all the way down", 1),
    ("adjust the lamp setting to high", 1), ("adjust the lamp setting to low", 1), ("more power to the lamp", 1), ("less power to the lamp", 1),
    ("speed up the photon emission", 1), ("slow down the photon emission", 1), ("maximize the light output", 1), ("minimize the light output", 1),
    ("the lamp is too dim speed it up", 1), ("the lamp is too bright slow it down", 1), ("put the lamp on max power", 1), ("put the lamp on min power", 1),
    ("accelerate the desk illumination", 1), ("decelerate the desk illumination", 1), ("give me full blast lamp", 1), ("gentle glow on the lamp", 1),
    ("make the lamp super bright", 1), ("make the lamp super dim", 1),

    # ==========================================
    # CLASS 2: CAMERA (250 Sentences)
    # ==========================================
    ("turn on the camera", 2), ("switch on the camera", 2), ("start the camera", 2), ("can you start the camera", 2),
    ("power on the camera", 2), ("activate the camera", 2), ("boot up the camera", 2), ("get the camera going", 2),
    ("spin up the camera sensor", 2), ("kick on the camera", 2), ("turn off the camera", 2), ("switch off the camera", 2),
    ("stop the camera", 2), ("can you stop the camera", 2), ("power off the camera", 2), ("deactivate the camera", 2),
    ("shut down the camera", 2), ("kill the camera", 2), ("turn the camera off", 2), ("cut the camera power", 2),
    ("i need to monitor the room", 2), ("start surveillance", 2), ("begin recording video", 2), ("watch the space", 2),
    ("keep an eye on the door", 2), ("stream the live feed", 2), ("open the video stream", 2), ("turn on security monitoring", 2),
    ("i want to check the perimeter", 2), ("record this moment", 2), ("capture a video clip", 2), ("start the optic tracking", 2),
    ("monitor the entryway", 2), ("turn on the webcam", 2), ("deactivate security logging", 2), ("shut down the lens", 2),
    ("is anyone outside", 2), ("show me the feedback look", 2), ("observe the laboratory setup", 2), ("capture an image", 2),
    ("increase camera resolution", 2), ("make the camera pan faster", 2), ("crank up the camera contrast", 2), ("turn up the exposure", 2),
    ("set camera frame rate to high", 2), ("zoom in the camera", 2), ("make the lens zoom close", 2), ("boost video gain", 2),
    ("put the zoom on max", 2), ("widen the camera view", 2), ("decrease camera resolution", 2), ("zoom out the lens", 2),
    ("turn down exposure", 2), ("slow down the camera pan", 2), ("set frame rate to low", 2), ("reduce video contrast", 2),
    ("make the lens pull back", 2), ("lower the camera sensitivity", 2), ("put zoom on minimum", 2), ("less exposure please", 2),
    ("pan the camera left", 2), ("tilt the camera down", 2), ("turn on motion tracking", 2), ("start face detection", 2),
    ("make the camera follow me", 2), ("stop camera tracking", 2), ("keep the camera fixed", 2), ("stop lens autofocus", 2),
    ("lock camera position", 2), ("make the lens stay still", 2), ("toggle the camera", 2), ("change the camera mode", 2),
    ("reset the camera", 2), ("check the camera status", 2), ("is the camera recording", 2), ("the security lens needs to start", 2),
    ("power up security camera", 2), ("shut off security camera", 2), ("webcam on", 2), ("webcam off", 2),
    ("cctv on", 2), ("cctv off", 2), ("start the cctv feed", 2), ("kill the cctv network", 2),
    ("the visual sensor is required", 2), ("disengage the camera", 2), ("engage the camera", 2), ("run the camera script", 2),
    ("execute camera command", 2), ("the surveillance loop is blind", 2), ("clear out the camera buffer", 2), ("freshen up the video frame", 2),
    ("initialize image capture", 2), ("get some video moving", 2), ("run the optics pipeline", 2), ("initiate camera sequence", 2),
    ("terminate camera process", 2), ("camera zoom up", 2), ("camera zoom down", 2), ("kill the camera feed", 2),
    ("please start the camera", 2), ("activate the camera lens", 2), ("make the camera record everything", 2), ("can you switch the camera", 2),
    ("kick off the security camera", 2), ("boot up the webcam camera", 2), ("toggle the camera power", 2), ("power on the surveillance camera", 2),
    ("switch on the backyard camera", 2), ("the camera needs to be turned on", 2), ("go ahead and start the camera", 2), ("engage the camera shutter", 2),
    ("crank up the camera resolution", 2), ("get the camera streaming now", 2), ("enable the monitoring camera", 2), ("turn the camera to online", 2),
    ("begin recording with camera", 2), ("fire up the porch camera", 2), ("set the camera to active", 2), ("start up the live camera", 2),
    ("run the camera on standby", 2), ("switch the camera to motion sensor", 2), ("wake up the security camera", 2), ("give me some eyes turn on the camera", 2),
    ("it is getting suspicious start the camera", 2), ("blind spot out there activate the camera", 2), ("need to monitor spin the camera", 2), ("make the camera capture video", 2),
    ("turn on the camera immediately", 2), ("could you please turn on the camera", 2), ("would you mind starting the camera", 2), ("execute camera start command", 2),
    ("unleash the camera feed", 2), ("get the dash camera going", 2), ("turn on the camera right away", 2), ("power up the house camera", 2),
    ("start the camera in the yard", 2), ("turn on the camera for me", 2), ("kick the camera into gear", 2), ("activate the main camera", 2),
    ("start the camera sensor", 2), ("switch on the front camera", 2), ("turn on the camera please", 2), ("let us get the camera recording", 2),
    ("power on the giant camera", 2), ("activate the room camera", 2), ("turn on the camera unit", 2), ("engage the camera power now", 2),
    ("please stop the camera", 2), ("deactivate the camera lens", 2), ("make the camera shut down", 2), ("can you stop the camera", 2),
    ("kill the security camera", 2), ("shut down the webcam camera", 2), ("toggle the camera off", 2), ("power off the surveillance camera", 2),
    ("switch off the backyard camera", 2), ("the camera needs to be turned off", 2), ("go ahead and stop the camera", 2), ("disengage the camera lens", 2),
    ("crank down the camera resolution", 2), ("get the camera to stop streaming", 2), ("disable the monitoring camera", 2), ("turn the camera to offline", 2),
    ("cease recording with camera", 2), ("cut power to the porch camera", 2), ("set the camera to inactive", 2), ("halt the live camera", 2),
    ("stop the camera completely", 2), ("switch the camera off entirely", 2), ("put the security camera to sleep", 2), ("the perimeter is secure turn off the camera", 2),
    ("i am inside now turn off the camera", 2), ("it is safe inside deactivate the camera", 2), ("the event ended stop the camera", 2), ("it feels private spin the camera off", 2),
    ("i need some privacy turn off the camera", 2), ("blind the lens stop the camera", 2), ("it is bright daylight activate the camera shutdown", 2), ("no more intruders stop the camera", 2),
    ("the guard arrived turn off the camera", 2), ("unbearably safe stop the camera", 2), ("quiet day activate the camera shutdown", 2), ("i am wrapping up spin the camera down", 2),
    ("the house needs privacy turn off the camera", 2), ("no more recording start the camera shutdown", 2), ("monitoring finished deactivate the camera", 2), ("safe environment spin the camera down", 2),
    ("need to block the feed turn off the camera", 2), ("the threat passed stop the camera", 2), ("it is an empty yard deactivate the camera", 2), ("i am turning off the monitor spin the camera off", 2),
    ("too many alerts everywhere turn off the camera", 2), ("false alarms are high stop the camera", 2), ("uncomfortable surveillance deactivate the camera", 2), ("need to stop the sensor spin the camera off", 2),
    ("increase the camera frame rate", 2), ("decrease the camera frame rate", 2), ("make the camera zoom in", 2), ("make the camera zoom out", 2),
    ("boost the camera exposure", 2), ("lower the camera exposure", 2), ("crank the camera resolution all the way up", 2), ("crank the camera resolution all the way down", 2),
    ("adjust the camera setting to high sensitivity", 2), ("adjust the camera setting to low sensitivity", 2), ("more power to the camera", 2), ("less power to the camera", 2),
    ("speed up the shutter speed", 2), ("slow down the shutter speed", 2), ("maximize the field of view", 2), ("minimize the field of view", 2),
    ("the camera is too blurry adjust focus", 2), ("the camera is too bright adjust contrast", 2), ("put the camera on max quality", 2), ("put the camera on min quality", 2),
    ("accelerate the pan tilt zoom", 2), ("decelerate the pan tilt zoom", 2), ("give me full resolution camera", 2), ("night vision mode on the camera", 2),
    ("make the camera super responsive", 2), ("make the camera super low power", 2),

    # ==========================================
    # CLASS 3: GOOGLE (250 Sentences)
    # ==========================================
    ("run search query on google", 3), ("please ask google", 3), ("activate the google search", 3), ("make google find an answer", 3),
    ("can you look up on google", 3), ("kick off the google engine", 3), ("boot up the google query", 3), ("toggle the google assistant", 3),
    ("power on the google browser", 3), ("switch on the google speaker", 3), ("the google needs to be turned on", 3), ("go ahead and start google", 3),
    ("engage the google application", 3), ("crank up the google search text", 3), ("get google searching now", 3), ("enable the google home", 3),
    ("turn the query to google", 3), ("begin surfing with google", 3), ("fire up the kitchen google", 3), ("set google to active", 3),
    ("start up the live google query", 3), ("run google on standby", 3), ("switch google to listening mode", 3), ("wake up the google device", 3),
    ("initiate the google sequence", 3), ("give me some information turn on google", 3), ("it is getting confusing start google", 3), ("knowledge gap here activate google", 3),
    ("need to verify look up google", 3), ("make google fetch data", 3), ("turn on google immediately", 3), ("could you please start google", 3),
    ("would you mind starting google", 3), ("execute google search command", 3), ("unleash the google web index", 3), ("get the desk google going", 3),
    ("turn on google right away", 3), ("power up the home google", 3), ("start google in the room", 3), ("turn on google for me", 3),
    ("kick google into gear", 3), ("activate the main google app", 3), ("start the google service", 3), ("switch on the front google", 3),
    ("turn on google please", 3), ("let us get google tracking", 3), ("power on the giant google", 3), ("activate the room google", 3),
    ("turn on the google unit", 3), ("engage google power now", 3), ("turn off google", 3), ("please stop google", 3),
    ("deactivate the google search", 3), ("make google shut down", 3), ("can you stop google", 3), ("kill the google engine", 3),
    ("shut down the google query", 3), ("toggle google off", 3), ("power off the google browser", 3), ("switch off the google speaker", 3),
    ("the google needs to be turned off", 3), ("go ahead and stop google", 3), ("disengage the google application", 3), ("crank down the google search text", 3),
    ("get google to stop searching", 3), ("disable the google home", 3), ("turn google to offline", 3), ("cease surfing with google", 3),
    ("cut power to the kitchen google", 3), ("set google to inactive", 3), ("halt the live google query", 3), ("stop google completely", 3),
    ("switch google off entirely", 3), ("put the google device to sleep", 3), ("terminate the google sequence", 3), ("i know the answer turn off google", 3),
    ("no more questions stop google", 3), ("clear understanding here deactivate google", 3), ("no need to verify stop google", 3), ("make google stop fetching", 3),
    ("turn off google immediately", 3), ("could you please turn off google", 3), ("would you mind stopping google", 3), ("execute google stop command", 3),
    ("cut the google web index", 3), ("get the desk google to stop", 3), ("turn off google right away", 3), ("power down the home google", 3),
    ("stop google in the room", 3), ("turn off google for me", 3), ("kick google out of gear", 3), ("deactivate the main google app", 3),
    ("stop the google service", 3), ("switch off the front google", 3), ("turn off google please", 3), ("let us stop google tracking", 3),
    ("power off the giant google", 3), ("deactivate the room google", 3), ("turn off the google unit", 3), ("disengage google power now", 3),
    ("what is the weather forecast for today", 3), ("will it rain this afternoon", 3), ("check the temperature outside", 3), ("is it going to be hot tomorrow", 3),
    ("google what is the weather like in New York", 3), ("do i need an umbrella today", 3), ("open my gmail inbox", 3), ("check my latest emails", 3),
    ("did i get any new mail from my boss", 3), ("google search for chicken breast recipes", 3), ("look up the definition of photosynthesis", 3), ("search the web for local coffee shops", 3),
    ("find the nearest gas station on the map", 3), ("what is on my calendar for this week", 3), ("do i have any meetings scheduled today", 3), ("remind me to buy milk at five pm", 3),
    ("set an alarm for seven am tomorrow", 3), ("translate hello to spanish", 3), ("how do you say thank you in french", 3), ("what is the stock price of apple", 3),
    ("who won the football match yesterday", 3), ("google find flights from delhi to london", 3), ("what time does the supermarket close", 3), ("how far is the moon from earth", 3),
    ("tell me a funny joke google", 3), ("what is the current population of india", 3), ("how do i fix a leaky faucet", 3), ("search for top movies of this year", 3),
    ("open google maps and give me directions", 3), ("check my unread notifications in mail", 3), ("did my package get delivered check email", 3), ("search for standard transformer neural networks", 3),
    ("what is the capital of australia", 3), ("google list the ingredients for baking a cake", 3), ("show me news about artificial intelligence", 3), ("is there traffic on my way to work", 3),
    ("how many centimeters are in an inch", 3), ("convert fifty dollars to euros", 3), ("what is the square root of 144", 3), ("google find articles on linear algebra", 3),
    ("read my last received email out loud", 3), ("search for cheap hotels near the beach", 3), ("what is the meaning of life", 3), ("who wrote the book crime and punishment", 3),
    ("check if the gym is open today", 3), ("google look up the symptoms of a cold", 3), ("find a tutorial on python loops", 3), ("what day of the week is halloween", 3),
    ("is it winding outside check weather", 3), ("send a quick email draft via gmail", 3), ("search the internet for breaking news", 3), ("how tall is Mt Everest", 3),
    ("i have a burning question look up google", 3), ("i am curious search google", 3), ("it is a mystery activate google", 3), ("the trivia is tough start google", 3),
    ("it feels confusing browse google", 3), ("i need a definition turn on google", 3), ("find the coordinates start google", 3), ("it is a complex problem activate google", 3),
    ("wondering about history query google", 3), ("the facts are missing turn on google", 3), ("unbearably curious start google", 3), ("puzzling day activate google", 3),
    ("i am lost spin google", 3), ("the assignment needs research turn on google", 3), ("data source needed start google", 3), ("sun distance logic activate google", 3),
    ("stifling confusion browse google", 3), ("need explanation turn on google", 3), ("the details are vague start google", 3), ("it is a riddle activate google", 3),
    ("i am straining my brain query google", 3), ("unknown concepts everywhere turn on google", 3), ("daylight is fading start google tracking", 3), ("uncomfortable ignorance activate google", 3),
    ("need the encyclopedia scan google", 3), ("i am done studying turn off google", 3), ("i got the facts turn off google", 3), ("it is fully answered deactivate google", 3),
    ("the homework is done stop google", 3), ("it feels solved turn google off", 3), ("i need to sleep turn off google", 3), ("stop the information flow stop google", 3),
    ("it is brutally clear deactivate google", 3), ("no more reading run google shutdown", 3), ("the brain is full turn off google", 3), ("unbearably knowledgeable stop google", 3),
    ("sufficient data activate google shutdown", 3), ("i am closing tabs spin google down", 3), ("the project is complete turn off google", 3), ("no more queries start google shutdown", 3),
    ("research finished deactivate google", 3), ("facts verified spin google down", 3), ("need to block internet turn off google", 3), ("the curiosity passed stop google", 3),
    ("it is an open book deactivate google", 3), ("i am turning off assistant spin google off", 3), ("too many notifications everywhere turn off google", 3), ("answers are complete stop google", 3),
    ("uncomfortable connectivity deactivate google", 3), ("need to stop the voice engine spin google off", 3), ("increase the google search volume", 3), ("decrease the google search volume", 3),
    ("make google go deeper", 3), ("make google go shallow", 3), ("boost the google tracking", 3), ("lower the google tracking", 3),
    ("crank the google assistant all the way up", 3), ("crank the google assistant all the way down", 3), ("adjust the google setting to maximum privacy", 3), ("adjust the google setting to low privacy", 3),
    ("more power to google", 3), ("less power to google", 3), ("speed up the query resolution", 3), ("slow down the query resolution", 3),
    ("maximize the database reach", 3), ("minimize the database reach", 3), ("the google is too slow clear cache", 3), ("the google is too loud lower voice", 3),
    ("put google on max speed", 3), ("put google on min speed", 3), ("accelerate the speech recognition", 3), ("decelerate the speech recognition", 3),
    ("give me full index google", 3), ("safe search mode on the google", 3), ("make google super smart", 3), ("make google super brief", 3)
]
